---
- name: Download desknet's NEO
  get_url:
    url: "{{ dneo_download_url }}"
    dest: "/tmp/{{ dneo_filename }}"

- name: Unarchive the tarball
  unarchive:
    src: "/tmp/{{ dneo_filename }}"
    dest: /var/www/cgi-bin/
    remote_src: yes
    creates: /var/www/cgi-bin/dneosp

- name: Move static contents
  shell: mv /var/www/cgi-bin/{{ item }} /var/www/html/.
  with_items:
    - "dneo/dneores"
    - "dneo/dneowmlroot"
    - "dneosp/dneospres"
  args:
    creates: /var/www/html/dneospres

#psql -d template1 -c "CREATE USER dneo WITH PASSWORD 'desknetsNeo_PgSql' CREATEROLE"
- name: Create postgresql user
  postgresql_user:
    db: template1
    login_user: "{{ postgres_su_user }}"
    login_password: "{{ postgres_su_pass }}"
    name: dneo
    password: desknetsNeo_PgSql
    priv: "ALL"

- name: Check dneo database
  shell: "psql -l | grep dneodb | wc -l"
  register: dneodb_exist
  become_method: su
  become_user: "{{ postgres_su_user  }}"
  changed_when: False

#pg_restore -C -Fc -d template1 /var/www/cgi-bin/dneo/dump/dneodb.pgdmp
- name: Restore dneo database
  shell: "pg_restore -w -U {{ postgres_su_user }} -C -Fc -d template1 /var/www/cgi-bin/dneo/dump/dneodb.pgdmp"
  when: dneodb_exist.stdout == "0"

- name: Check accesslog database
  shell: "psql -l | grep dneologdb | wc -l"
  register: dneologdb_exist
  become_method: su
  become_user: "{{ postgres_su_user  }}"
  changed_when: False

#pg_restore -C -Fc -d template1 /var/www/cgi-bin/dneo/dump/dneologdb.pgdmp
- name: Restore accesslog database
  shell: "pg_restore -w -U {{ postgres_su_user }} -C -Fc -d template1 /var/www/cgi-bin/dneo/dump/dneologdb.pgdmp"
  when: dneologdb_exist.stdout == "0"

#psql -d template1 -c "CREATE USER dneofts WITH PASSWORD 'dneofts' CREATEROLE"
- name: Create file search role
  postgresql_user:
    db: template1
    login_user: "{{ postgres_su_user }}"
    login_password: "{{ postgres_su_pass }}"
    name: dneofts
    password: dneofts
    priv: "ALL"

- name: Check dneoftsdb database
  shell: "psql -l | grep dneoftsdb | wc -l"
  register: dneoftsdb_exist
  become_method: su
  become_user: "{{ postgres_su_user  }}"
  changed_when: False

#pg_restore -C -Fc -d template1 /var/www/cgi-bin/dneo/dump/dneoftsdb.pgdmp
- name: Restore file search database
  shell: "pg_restore -w -U {{ postgres_su_user }} -C -Fc -d template1 /var/www/cgi-bin/dneo/dump/dneoftsdb.pgdmp"
  when: dneoftsdb_exist.stdout == "0"
