---
- name: Install phpPgAdmin
  yum:
    state: present
    enablerepo: epel
    name: phpPgAdmin

#- name: Allow http
#  firewalld:
#    systemd: http
#    permanent: true
#    state: enabled
#    immediate: yes

- name: Start and enable httpd
  systemd:
    name: httpd
    state: started
    enabled: yes
