- name: Apache(httpd) インストール
  yum:
    name: httpd
    state: present

- name: httpd.conf 設定
  template:
    src: templates/httpd.conf.j2
    dest: /etc/httpd/httpd.conf
    owner: root
    group: root
    mode: 0644

- name: サービス 設定
  systemd:
    name: httpd
    state: started
    enabled: yes
