- name: Install httpd
  yum:
    name: httpd
    state: present

- name: Copy httpd.conf
  template:
    src: templates/httpd.conf.j2
    dest: /etc/httpd/httpd.conf
    owner: root
    group: root
    mode: 0644

- name: Set automatic start of httpd
  systemd:
    name: httpd
    state: started
    enabled: yes
