---
- name: Get status whethere db cluster is exist or not
  stat: 
    path: /var/lib/pgsql/9.6/data/PG_VERSION
  register: dbcluster

- name: Create a new PostgreSQL database cluster
  shell: /usr/pgsql-9.6/bin/initdb -D /var/lib/pgsql/9.6/data --no-locale
  become: yes
  become_user: postgres
  when: not dbcluster.stat.exists

- name: Start and enable PostgreSQL
  systemd:
    name: postgresql-9.6.service 
    state: started
    enabled: yes

- name: Copy pg_hba.conf
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/9.6/data/pg_hba.conf
    backup: yes
  notify: Restart postgresql-9.6

- name: Install psycopg2
  yum:
    name: python-psycopg2
    state: latest
    
- name: Set password to database superuser
  postgresql_user:
    user: "{{ postgres_su_user }}"
    password: "{{ postgres_su_pass }}"
    login_password: "{{ postgres_su_pass }}"
  notify: Restart postgresql-9.6

- name: Set password file
  template:
    src: templates/.pgpass.j2
    dest: /root/.pgpass
    owner: root
    group: root
    mode: 0600
